### ISSUE TITLE
  The app you were looking for is not available anymore

### ISSUE THREAD

**Issue by kamabhavik** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#1]
I got following message when i try to open the url in safari browser just after creating the link.
"The app you were looking for is not available anymore. It might has been deleted. Please refer to your app developer for any question."

Please let me know what is going wrong in here?

**Comment by vineetchoudhary** [comment]
@kamabhavik sorry for late reply, This is generally happens if ipa or manifest file deleted from your Dropbox account.

**Comment by vineetchoudhary** [comment]
Or due to a bug in current public release with multiple info.plist in project (may be 3rd party lib info.plist). I've fixed for that in this Alpha release.

https://iosappswirelessinstallation.codeplex.com/downloads/get/1622425

**Comment by vineetchoudhary** [comment]
Hi @kamabhavik did this (https://iosappswirelessinstallation.codeplex.com/downloads/get/1622425) version update solve the issue for you?

**Comment by vineetchoudhary** [comment]
Closing this issue as haven't heard from you. Feel free to open it again at a later time. =)
