### ISSUE TITLE
ReadMe 

### ISSUE THREAD

**Issue by Sam-Ryan** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#101]
Hi man, 
I want to use your project for hosting on my website then i can use my self the script and i want to couple with my script  of url shortener https://github.com/Sam-Ryan/YouShort
Look around the code and found some key to replace but can you please provide a readme on how to use for self hosting the script?

**Comment by Sam-Ryan** [comment]
Hi man,

I just want to currently build the same project to host on my server the tryapp.github page and the service.
Is this tutorial you send me will currently help me to build this? Thanks

**Comment by vineetchoudhary** [comment]
>Is this tutorial you send me will currently help me to build this?
No. That was for Jenkins CI and CD.

Currently, I don't have any document to customize the installation page (tryapp.github.io) and AppBox for same. In most of the places, I'm using hardcoded values. I started this as a side project in my learning phase.

Hopefully, somewhere in near feature, I'll provide the option to customize all these kind fields from UI. 

So, for now, you need to make changes in those hardcode values.

**Comment by vineetchoudhary** [comment]
No, URL is managed by short URL services. So, It can't be modified.
