### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#103]
Hello, I would like to design a logo for your project. Do you have something on your mind for your logo?  I can give some ideas if you are interested?
Greetings
Nuno

**Comment by vineetchoudhary** [comment]
Hi Nuno,
I'm interested. The current logo is just a distorted version of Testflight logo. 🤣🤣🤣
I don't have any specific requirement for the logo. You can use your creativity. 😃 
I just need a log that define the project and project title (AppBox - Build, Test, and Distribute iOS Application). 

Thank You

**Comment by nunojesus** [comment]
Hi,
To design the logo I need to know a few things, such as:
 - Which color do you prefer? 
- The app is for Build, Test, and Distribute, so I should focus on these three tools, which the app does, right?

You can contact me on: 
telegram:  https://t.me/nunojesus
e-mail: jesus.nunojose@gmail.com

Greetings
Nuno

**Comment by nunojesus** [comment]
Hi, I create this pull request with the logo design proposal, just check it!

https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/pull/104

**Comment by nunojesus** [comment]
![versonii](https://user-images.githubusercontent.com/34600369/38987734-be6081e6-43c8-11e8-934e-68e177eb8e13.png)

Hi, Look if you like this? 
In this logo you have the first element is the Box because the application is called APPBOX, and the three elements Built, Test and Destribute elements and represented by the color square and the 2 triangle.

See if you like this one.

Greetings 

Nuno

**Comment by nunojesus** [comment]
I forget to say that the < > of code are also represented :)

**Comment by nunojesus** [comment]
![untitled-2](https://user-images.githubusercontent.com/34600369/38988842-973a39c8-43cc-11e8-89dd-ae36f730694c.png)

And I have this one too.

**Comment by vineetchoudhary** [comment]
Hi, 

Please check the attached icons in this [comment](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/103#issuecomment-382614016). That zip file contains icons of Xcode, Simulator, and VSCode, please take them as a reference. Just try to replace that hammer in Xcode icon with this  [icon](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/files/1927962/tools.psd.zip). 


 **Also, this application only for macOS, not for iOS or Android.**

**Comment by nunojesus** [comment]
Hello, what you're asking me to do is plagiarize, this I can not do, I'll make another logotype with your indications, to see if you like.

**Comment by nunojesus** [comment]
Here Is a new proposal
![appbox](https://user-images.githubusercontent.com/34600369/38998894-7795e2ea-43e8-11e8-86f5-1e2fcc08459b.png)
