### ISSUE TITLE
Installation page is loading when dropbox is blocked by browser

### ISSUE THREAD

**Issue by iTamilan** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#105]
Sometimes I got the feedback from users that Appbox link is not working. I got the feedback like the page is still loading and not displaying anything. And that is due to a browser or firewall is blocking then Dropbox URL, in that case, it is still loading.

Sometimes I even shared the ipa file directly to the user due to this issue.

**Comment by vineetchoudhary** [comment]
I'll check the possible solution to tackle this problem.

**Comment by vineetchoudhary** [comment]
Released in [2.6.0](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.6.0) with new domain https://web.getappbox.com
