### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by toseefkhilji** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#107]
## Description
Thanks for the great tool.
It would be great if you show app icon on installation screen as well as on device home Screen.

## Steps to Reproduce
1. Not required

## Details

1. Which AppBox version are you using?
    - [X] 2.5.0
    

2. Which macOS version did you experience the issue on?
    - [X] macOS 10.13.x

**Comment by vineetchoudhary** [comment]
Hi @toseefkhilji 
Will be available in next version as an optional feature.

**Comment by toseefkhilji** [comment]
Thanks

**Comment by vineetchoudhary** [comment]
I've tried to implement this but looks like Apple doesn't support permanent redirect (HTTP status 301) for icons file. I've tried this with amazon s3 and everything working fine. But I don't want user data on the personal server.

For now, I'm closing this issue.
