### ISSUE TITLE
Unable to install "App Name". Please try again later.

### ISSUE THREAD

**Issue by dpsLoner** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#112]
After I uploaded my .ipa file to AppBox i gave the the url and i use that url to install from Safari.
After the download completed, it's unable to install the app with the Alert

Unable to install "---"
Please try again later.

**Comment by ipwnosx** [comment]
I’ve got a a paid developer account  and that all that’s ever happened since I’m day one of trying that

**Comment by vineetchoudhary** [comment]
HI, 

Make sure you've added your device UDID on your Apple Developer Account.

![screen shot 3](https://user-images.githubusercontent.com/8479436/44087361-3b1ba420-9fdd-11e8-92bd-92d82a86b475.png)

![screen shot 4](https://user-images.githubusercontent.com/8479436/44087354-351752b8-9fdd-11e8-8a93-911b5f902ca6.png)

**Comment by vineetchoudhary** [comment]
ok. 🤣 
Check your IPA file have your device UDID. To check this you need to open AppBox. 
1. Click on File Menu
2. Click on Dashboard
3. Now select build, for which you want to know the UDID.
4. Click on Provisioning Profile Option
5. Here you'll see this window
<img width="958" alt="screen shot 2018-08-15 at 11 57 34 am" src="https://user-images.githubusercontent.com/8479436/44134422-7f637eb4-a082-11e8-8ff4-2806c0b6c3d2.png">
6. Here you can copy all provisioned device UDID by clicking on "Copy all Provisioned Device UUID". (lol typo UUID)
7. Copy paste them in some text file and check your device UDID present there.

**Comment by vineetchoudhary** [comment]
This issue has been closed. If you still have this issue feel free to reopen.

**Comment by NehaEnstrapp** [comment]
Hello,

I am using distribution provision profile and certificates. I generated .ipa file using distribution certificate and provision profile and uploaded on my MDM server. When I am trying to install the app, it is saying ,

"Unable to install the app
Please try again later"

Any solution for this.

Thanks in advance!

**Comment by vineetchoudhary** [comment]
Hi @NehaEnstrapp ,

Make sure you have that device UDID in the provisioning profile.

Also, just a question, how you are using AppBox link with the MDM server?

**Comment by NehaEnstrapp** [comment]
Hello Vineet,

For distribution profile, UDIDs are not required.
I just uploaded my .ipa file on my MDM server.

My client doesn't want to upload it on app store for internal distribute , how they can distribute the app with app store upload?

Apple does not allow to create enterprise account, apple is suggesting to generate apple business manager.

What can be the next step?

Thanks in advance

**Comment by vineetchoudhary** [comment]
Hi, for Ad-hoc distribution you need UDIDs but I think Ad-hoc is not an option for you.  So, an enterprise account is the only option if you don't want to go with Apple Business Manager.

**Comment by NehaEnstrapp** [comment]
Hello,
But Apple team is not allowing us to generate Enterprise Account as they are saying for all new accounts you have to enrol for Business Manager Account.

Thanks in Advance!

**Comment by vineetchoudhary** [comment]
Ohhh... I didn't know that. Most probably due to current misuse by companies like Facebook, Cambridge Analytica, etc... Thanks for the information. 

**Just for the note** - AppBox only provides a way for Apps Wireless Installation with a valid provisioning profile only.

**Alternative Solution** - You can build a custom solution using [AltStore](https://github.com/rileytestut/AltStore). Currently, I don't know if it's work with MDM Server or not.

**Comment by NehaEnstrapp** [comment]
ok .. Thanks for the information.

**Comment by mesas978** [comment]
My iPhone has a Serial Number, an IMEI, a ICCID. 
Is the serial the same as the UDID?
I'm told you have to attach the iPhone to a macbook to get the UDID for security reasons (?)
