### ISSUE TITLE
Unable to Download App

### ISSUE THREAD

**Issue by sayedzakrea** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#114]
hi,
i get this error while i trying to install app on device i use App Store Distribution

Unable to Download App
"App Name" could not be installed at this time.

**Comment by vineetchoudhary** [comment]
Please check this https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/112

**Comment by vineetchoudhary** [comment]
Hi, I'm closing this issue. If #112 doesn't cover your case please feel free to open this issue.
