### ISSUE TITLE
Add an option for Adding team

### ISSUE THREAD

**Issue by shahidlatif2007** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#115]
Add an option for adding team instead of typing email addresses every time.

**Comment by vineetchoudhary** [comment]
For a very long time, we have had the option to store email addresses and custom message. I don't feel we need to create a team entity as It'll create an additional maintenance burden on the project. If anyone from the community wants to create and maintain the feature then PR is most welcome.
