### ISSUE TITLE
AppBox App Download link not working

### ISSUE THREAD

**Issue by GauravRockers** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#119]
I have create AppBox link to install my iOS Application. I have Added 26 Devices to my Adhoc Distribution Provisioning profile to access my app to download into their device. Link is working in 23 device to install but 2 iPhone devices is from Egypt and they are not able to download app using the link I given. Whenever they try to install app, just loading icon appears.

**Comment by shahidlatif2007** [comment]
Can you send them and ask them to manually installed on there device? I think may be device ids has not beed added for those devices.

**Comment by GauravRockers** [comment]
Device Ids added for those devices, So that's not the issue.


Thank You
*Gaurav Panchal (iOS Developer)*

**Comment by vineetchoudhary** [comment]
Please make sure Github and Dropbox are accessible in Egypt.

**Comment by shahidlatif2007** [comment]
Application should show error popup if Github and Dropbox are not accessible.

**Comment by vineetchoudhary** [comment]
Yes, I'm working on it now. I'll update the installation web app by this weekend.

**Comment by vineetchoudhary** [comment]
Duplicate https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/105

**Comment by vineetchoudhary** [comment]
Hi, 
I made some changes on the web installation page to check Dropbox is blocked or not. Can you help me to test this? Here the development domain https://dev.web.getappbox.com/. In this domain just append your build URL (`?url=%2Fs%2...appinfo.json`) and check.

**Like** - https://dev.web.getappbox.com/?url=%2Fs%2...appinfo.json
