### ISSUE TITLE
download page customization?

### ISSUE THREAD

**Issue by dkliman** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#14]
is there an easy way to completely customize the download app page that's generated so that it has my own design?

**Comment by vineetchoudhary** [comment]
Hi @dkliman, currently we are using vary basic installation page available here https://github.com/TryApp/tryapp.github.io and also hosted from github.

You can create own page in same way. In current (appbox version)[https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/latest] you just need to add your own url [here](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/blob/master/AppBox/ViewController/HomeViewController/HomeViewController.m#L611) and [here](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/blob/master/AppBox/ViewController/HomeViewController/HomeViewController.m#L626).

```objective-c
-(void)createUniqueShortSharableUrl{
    NSString *originalURL = [project.uniquelinkShareableURL.absoluteString componentsSeparatedByString:@"dropbox.com"][1];
    .....
    [Tiny shortenURL:[NSURL URLWithString:[NSString stringWithFormat:@"https://tryapp.github.io?url=%@",originalURL]] withService:service completion:^(NSURL *shortURL, NSError *error) {
        .....
    }];
}
```

We'll provide a option in future release to change this url from app.

**Contribute Please**
If you want to make your designe default for appbox installation page. Fork the https://github.com/TryApp/tryapp.github.io and put your code in [devindex.html](https://github.com/TryApp/tryapp.github.io/blob/master/devindex.html).

I've very basic knowledge of web development. Please contribute your design.

Thanks

**Comment by dkliman** [comment]
thanks for all of that!

for now I was just simply making a birthday card for my dad, and wanted a nice looking page for him, so it's very custom... I don't even write in html, but i guess i figured it out pretty easily... if i come up with something a little more generic i'll fork it... :-)

**Comment by vineetchoudhary** [comment]
Hi @dkliman did you check latest app installation web page? How's now?

**Comment by dkliman** [comment]
I'll take a look!

**Comment by Sam-Ryan** [comment]
Thanks Man will check that in a moment 👍🏽

**Comment by trungnguyen1791** [comment]
@vineetchoudhary Are there any option to change the default design of installation page now?. I saw you deleted the devindex.html already :(

**Comment by vineetchoudhary** [comment]
Hi @trungnguyen1791 , that repo moved to this https://github.com/getappbox/WebApp-Dev

**Comment by trungnguyen1791** [comment]
@vineetchoudhary thank you for a really fast reply 👍 
Could you tell me where can I replace the folk respository's url ( with custom index.html)?. Is this still in `createUniqueShortSharableUrl `

**Comment by vineetchoudhary** [comment]
@trungnguyen1791 , now that's not possible. You can replace it manually after the URL gets expended. Now, these things completely managed by branch.io.
