### ISSUE TITLE
Mouse pointer is on top of QR code after the QR code is clicked

### ISSUE THREAD

**Issue by tkirby** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#146]
Small QoL improvement:

Problem: Mouse pointer obscures QR code after QR code image is displayed. So if you click the QR button (and don't move the mouse after) then aim your camera at the image, sometimes it's not recognized.

Potential Solutions: 
1) Swap 'QR Code' and 'Copy Clipboard' buttons. Easiest
2) Hide mouse pointer on QR code open. A little non-standard
3) Open QR Code in a NSPopover below the button. This is probably most Apple-ish.
![popover](https://user-images.githubusercontent.com/43665/47990106-4140d500-e119-11e8-9c22-2d14f53bb535.jpeg)

**Comment by vineetchoudhary** [comment]
<img width="849" alt="screenshot 2018-11-06 at 7 29 41 pm" src="https://user-images.githubusercontent.com/8479436/48069186-d071e980-e1fa-11e8-8bcd-5d884666d274.png">
<img width="849" alt="screenshot 2018-11-06 at 7 29 47 pm" src="https://user-images.githubusercontent.com/8479436/48069187-d10a8000-e1fa-11e8-86b2-c686fcc87c31.png">

**Comment by vineetchoudhary** [comment]
Fixed. Will be available in [2.7.0](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/milestone/12).
