### ISSUE TITLE
One System To Another System , We need same IPA Url

### ISSUE THREAD

**Issue by ShambhooSevenstar** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#149]
One System To Another System , We need same IPA Url
If we have copy or Same appbox in other system it will not Create Same Link Url
Please Provide
Thanks

**Comment by vineetchoudhary** [comment]
Hi,

You need to log in with the same Dropbox account in another system. Because AppBox manages same link information within the Dropbox account.

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no further response from the author. If the above solution doesn't work, please reach out so that we can investigate further.
