### ISSUE TITLE
New Logo Design

### ISSUE THREAD

**Issue by vineetchoudhary** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#150]
Hi All,

AppBox needs a new logo. Please help 🙏 🙏

**Comment by toseefkhilji** [comment]
Something like : 
https://dribbble.com/shots/4837695-Energy-Box

**Comment by vineetchoudhary** [comment]
@toseefkhilji yes, maybe, but icon needs to look like for a developer related tool.

**Comment by toseefkhilji** [comment]
Updated:
![energy_box code](https://user-images.githubusercontent.com/2367614/49855298-c1daab80-fe12-11e8-9846-7a14f5a5cba3.png)

**Comment by vineetchoudhary** [comment]
that will be great but I don't think so this icon is royalty free. Also, you can take refrences from Xcode Instruments app - 

![screenshot 2](https://user-images.githubusercontent.com/8479436/49862567-6f09ef80-fe24-11e8-8fac-415a8844ca47.png)

![screenshot 4](https://user-images.githubusercontent.com/8479436/49862634-9a8cda00-fe24-11e8-9d30-c0e85cd43c10.png)

**Comment by toseefkhilji** [comment]
Yes, you are correct.
I'll  play with Allocations icon.
But required some answer what you think on below:

- Rounded or square ?
- Flat Color or Gradient ?
- Border needed ?

**Comment by vineetchoudhary** [comment]
- Rounded or square?
  - Rounded
Flat Color or Gradient?
  - Gradient if it looks better otherwise flat 
Border needed?
- Again, if it looks good with the border

For background, you can take reference of Realm Studio icon. Because those line in background represent that you are using this for something that's not ready yet or for development -  

<img width="512" alt="realm studio" src="https://user-images.githubusercontent.com/8479436/49865317-a1b6e680-fe2a-11e8-95b8-4ae1fc20721d.png">

![image_43189](https://user-images.githubusercontent.com/8479436/49865540-36b9df80-fe2b-11e8-9114-fbda55f10264.jpg)


Here the great template - 
https://www.everyinteraction.com/resources/ios-10-11-app-icon-template-psd-sketch/

**Comment by toseefkhilji** [comment]
Adding images.
![1](https://user-images.githubusercontent.com/2367614/49997107-bcb66180-ffb6-11e8-98ad-cc8c1c058a31.png)
![2](https://user-images.githubusercontent.com/2367614/49997108-bd4ef800-ffb6-11e8-9287-d63c5693a029.png)

**Comment by vineetchoudhary** [comment]
I think the second one looks cool. Can you please make one with rounded corner instead of a circle. Or just create one in the square. What do you think?

**Comment by toseefkhilji** [comment]
Yeap. 2nd looks good. Tried to give in development style but I'm not a designer (Yet).

Adding Square Image:
![03](https://user-images.githubusercontent.com/2367614/50001034-9649f380-ffc1-11e8-82cc-b14a88f823dd.png)

**Comment by vineetchoudhary** [comment]
Great. 👍 
Thank you so much. 

If you've time, you can check more possibilities instead of `</>`. This looks great too. But here are some more resources which we can use instead of `</>`.

- https://www.flaticon.com/free-icon/smartphone_1230091 <- Cell Phone with upload icon (means upload the IPA file)
- https://www.flaticon.com/free-icon/cellphone_886590 <- Cell Phone with some app
- https://www.flaticon.com/free-icon/tools_771605 <- this represents a tool (like Xcode)

Also, if you want to change the color you can change right from flaticon UI - 

 
![screenshot 8](https://user-images.githubusercontent.com/8479436/50003640-605d3d00-ffca-11e8-8e9f-555100c99e18.png)

Also, please upload the raw file here. I'll update the appbox icon in next release with special thanks to you. 💯 

Again, Thank you 😊

**Comment by toseefkhilji** [comment]
what image size you require?

**Comment by vineetchoudhary** [comment]
1024*1024

**Comment by vineetchoudhary** [comment]
Thank You 😊 😊
