### ISSUE TITLE
Showing the blank image after installing in Production IPA and nothing happened when i click on it.

### ISSUE THREAD

**Issue by VenkateshSparsh** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#159]
Hi,

  I have uploaded the production .IPA to the AppBox, it generated me the link. When I try to download the application from link, it got downloaded. But can not able to open the application ,it shows an blank icon. Please help me to download an Production IPA build from link

**Comment by vineetchoudhary** [comment]
Hi, could you please provide some more details about the issue.  If it's possible please provide the app link and app installation icon screenshot. You can send me the app link via vineetchoudhary[at]live.in

**Comment by VenkateshSparsh** [comment]
Hi @vineetchoudhary , I have shared the information to your mail.

**Comment by vineetchoudhary** [comment]
Hi, As I found, you are using `AppStore Provisioning Profile` in your application. iOS doesn't allow to install the application with `AppStore Provisioning Profile` outside the `Apple iOS AppStore`. So, you need to sign your app with either `development`, `ad-hoc` or `enterprise` provisioning profile.


![2019-03-25 (1)](https://user-images.githubusercontent.com/8479436/54975758-27b40300-4fbe-11e9-86bd-2c85c6c27c5b.jpg)

**Comment by VenkateshSparsh** [comment]
Thanks for the explanation @vineetchoudhary , how to send the build to the testers with adding their UDID's to my developer and TestFlight. I want to send the build to the UAT team where we can not create the add the UDID and create the build every time. Please suggest me.

**Comment by vineetchoudhary** [comment]
If you don't know who and how many people going to test your application then I suggest you use `InHouse Provisioning Profile`(Enterprise). You can read more about the Apple Developer Enterprise Program [here](https://developer.apple.com/programs/enterprise/). It'll cost you $299/year.
