### ISSUE TITLE
Export Archive Failed - Not able to set provisioning profiles manually.

### ISSUE THREAD

**Issue by kunalverma25** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#160]
## Details

1. Which AppBox version are you using?
    - [X] 2.7.2
    - [ ] 2.7.1
    - [ ] 2.7.0
    - [ ] 2.6.1
    - [ ] 2.6.0
    - [ ] 2.5.0
    

2. Which macOS version did you experience the issue on?
    - [X] macOS 10.14.x
    - [ ] macOS 10.13.x
    - [ ] macOS 10.12.x
    - [ ] macOS 10.11.x
    - [ ] macOS 10.10.x

**Comment by vineetchoudhary** [comment]
Hi, can you please provide the logs. You can see the logs generated by AppBox in `File>View Log`.

![screen shot 4](https://user-images.githubusercontent.com/8479436/30270562-a14e42fc-970a-11e7-9dd7-096d54eb1698.png)

**Comment by vineetchoudhary** [comment]
Hi, currently, AppBox only able to build a project that has automatic signing enabled.

**Comment by kunalverma25** [comment]
You only need to add a couple of elements to add this functionality.

[exportOption setValue:@"manual" forKey:@"signingStyle"];

And then add a dictionary like -
NSMutableDictionary *profiles = [[NSMutableDictionary alloc] init];
[profiles setValue:@"Awesome App Provisioning Profile name" forKey:@"com.awesomeapp.ios"];
[profiles setValue:@"Awesome App Notification Provisioning Profile name" forKey:@"com.awesomeapp.notificationservice.ios"];
[exportOption setValue:profiles forKey:@"provisioningProfiles"];

Aand you're done!
Just add a couple fields in front-end..

**Comment by vineetchoudhary** [comment]
Yes, I know that. But automatic signing is there since Xcode 8 (i think). So, I dropped the plan of providing support for manual signing. Now, I'll rethink about this and try to support this for both manual build and CI&CD.

**Comment by kunalverma25** [comment]
Yeah I agree, But there are still cases, like different build schemes and identifiers, especially in large projects, that still depend on Manual signing. It'd be a great addition if can be done through UI itself.

**Comment by vineetchoudhary** [comment]
Yes. I agree with different bundle identifiers case. Because most of the time different schemes configuration file included in the project doesn't work at all. 

I'll surely work on the support of [manual signing](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/projects/1#card-19471457). Currently, I'm very busy with my full-time job.

**Comment by vincekinyops** [comment]
I am not sure if this question is related to this entire thread at all, but I'll be leaving it here nonetheless.
Do devices need to be registered to a provisioning profile in order for Appbox installation to be completed?

**Comment by vineetchoudhary** [comment]
> I am not sure if this question is related to this entire thread at all, but I'll be leaving it here nonetheless.
> Do devices need to be registered to a provisioning profile in order for Appbox installation to be completed?

Yes.

**Comment by vineetchoudhary** [comment]
In [version 3](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/tree/v3.0), we are going to remove the Archive feature completely from the AppBox as Fastlane is a much better option for this and [AppBox has a plugin for the Fastlane](https://github.com/getappbox/fastlane-plugin-appbox).
