### ISSUE TITLE
Errors due to a problem on the client-side of the SDK. Please try again.

### ISSUE THREAD

**Issue by toseefkhilji** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#162]
## Description
Getting Error while uploading new ipa.

## Steps to Reproduce
1. Open AppBox
2. Drag ipa file
3. upload ipa button click.

## Details

1. Which AppBox version are you using?
    - [X] 2.7.2
    - [ ] 2.7.1
    - [ ] 2.7.0
    - [ ] 2.6.1
    - [ ] 2.6.0
    - [ ] 2.5.0
    

2. Which macOS version did you experience the issue on?
    - [X] macOS 10.14.x
    - [ ] macOS 10.13.x
    - [ ] macOS 10.12.x
    - [ ] macOS 10.11.x
    - [ ] macOS 10.10.x
   
3. Crash Report
N/a

4. Screenshots

![Appbox version](https://user-images.githubusercontent.com/2367614/55552209-6b171b80-56fa-11e9-9668-66290ee56b6f.png)
![AppBox](https://user-images.githubusercontent.com/2367614/55552210-6b171b80-56fa-11e9-9655-a066fe51976e.png)

## AppBox Logs
<details>
  <summary><b>Logs</b></summary>
  <pre><code>
  DropBox Used Space : 805MB
DropBox Available Space : 2048MB
Extracting Files...
Uploading - SourceAbledCommunity.ipa
Upload DB Error - DropboxClientError[{
    NSError = "Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\" UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600001a20540 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <411E1175-FE99-4305-9CC6-3DC1C11E11F4>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalUploadTask <411E1175-FE99-4305-9CC6-3DC1C11E11F4>.<3>\"\n), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/upload, NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/upload, _kCFStreamErrorDomainKey=4}";
}]; 
 Route Error - (null)
ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.
Extracting Files...
Uploading - SourceAbledCommunity.ipa
Upload DB Error - DropboxClientError[{
    NSError = "Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x600001ba0f30 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <9BA1D045-3CF3-41D8-A7F4-F9A91A83FC59>.<4>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalUploadTask <9BA1D045-3CF3-41D8-A7F4-F9A91A83FC59>.<4>\"\n), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/upload, NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/upload, _kCFStreamErrorDomainKey=12}";
}]; 
 Route Error - (null)
ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.
  </code></pre>
</details>

## Additional context
This issue occurs many times. but After many try( approx. 5-6 time) , ipa successfully uploaded.

Thank You :)

**Comment by vineetchoudhary** [comment]
Hi, that strange. Did you get this error always or in the recent period? Because this is the clearly a DropBox SDK error or some Network Firewall Issue and If it's broken one time it's must be broken every time.

Can you please try to upload the same IPA file using dropbox.com web interface. Check if you got the same error. Meantime I'll try to reproduce this issue.

Also, please let me know, what's the size of the IPA file?

**Comment by toseefkhilji** [comment]
Hi @vineetchoudhary : It's random behaviour, Some time it gives error, some time it success.
IPA size is around 53 MB.

**Comment by vineetchoudhary** [comment]
IPA file size is normal. I've tested Appbox with approx 2.4GB IPA file. For now, I can only release the Appbox with updated Dropbox SDK.

**Comment by toseefkhilji** [comment]
@vineetchoudhary : Ok, Closing for now.

**Comment by gaminilesh** [comment]
Hello i am getting same error

ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.
Extracting Files...
Uploading - 2019.04.08_1.0.189 .ipa
Upload DB Error - DropboxClientError[{
    NSError = "Error Domain=NSURLErrorDomain Code=-1202 \"The certificate for this server is invalid. You might be connecting to a server that is pretending to be \U201capi-content.dropbox.com\U201d which could put your confidential information at risk.\" UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(\n    \"<cert(0x7f8adf006000) s: content.dropboxapi.com i: Cyberoam SSL CA>\",\n    \"<cert(0x7f8adf100000) s: Cyberoam SSL CA i: Cyberoam SSL CA>\"\n), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/upload, NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/upload, NSUnderlyingError=0x600001f22a60 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 \"(null)\" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x60000221c990>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9813, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9813, kCFStreamPropertySSLPeerCertificates=(\n    \"<cert(0x7f8adf006000) s: content.dropboxapi.com i: Cyberoam SSL CA>\",\n    \"<cert(0x7f8adf100000) s: Cyberoam SSL CA i: Cyberoam SSL CA>\"\n)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalUploadTask <96D7643D-7F34-41DF-B68F-7F2AE4B508CD>.<8>\"\n), _kCFStreamErrorCodeKey=-9813, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <96D7643D-7F34-41DF-B68F-7F2AE4B508CD>.<8>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x60000221c990>, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be \U201capi-content.dropbox.com\U201d which could put your confidential information at risk.}";
}]; 
 Route Error - (null)
ALERT -
Title - Error Message - Errors due to a problem on the client-side of the SDK. Please try again.

**Comment by shiiVaam** [comment]
Just logout and login APPBOX
