### ISSUE TITLE
Upload IPA from Command line without any user confirmation

### ISSUE THREAD

**Issue by satheeshpayoda** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#166]
## Is your feature request related to a problem? Please describe.
I'm using MSBuild in Jenkins to build Xamarin project and generate IPA file. So I need to upload to IPA alone to DropBox for local testing. Currently i'm using **ipa=** argument and passing IPA file location as argument to automate the upload process. 

Now i'm facing two issue: 
1. Once Upload completed or failed. AppBox UI is not getting closed. So Jenkins job is in running state forever. I have use timeout command to kill the app after X mins.
2. Sometimes because of User Confirmation dialog like New Version update dialog. Jenkins job is in running state forever.

## Describe the solution you'd like
There should be dedicated command line option to upload IPA alone to DropBox without any user interaction. It should close automatically when upload competed / failed. Also there should be an option to get final Share URL when successfully uploaded to Dropbox. My Opinion: You can set Environment variable to save Share URL. So jenkins can read the variable to get final URL.

Thanks.

**Comment by vineetchoudhary** [comment]
**Regarding Update Alert**
You can disable the update alert from AppBox CI Preferences. Open AppBox Preferences then Select CI Settings.

**Regarding Auto Close** 
I've handled most of the cases when you are using `ipa` or `build` arguments. I think you are facing this issue due to update alert. Please disable the update alert from CI Setting.

Let me know if you still face this issue after disabling update alert.

**Comment by satheeshpayoda** [comment]
Its disabled. I verified. 
But i tested on 2.7.2
Is this fixed on latest version?

**Comment by satheeshpayoda** [comment]
Reopening.... Closed by mistake.

**Comment by satheeshpayoda** [comment]
**Regarding Auto Close**
Its still not getting closed. I tested on latest version.
FYI, i'm calling this cmd to upload:
/Applications/AppBox.app/Contents/MacOS/AppBox ipa=$IPA_FILE

**Comment by vineetchoudhary** [comment]
Got this. You need to set an email address. You can set multiple commas separated email address. 

```bash
/Applications/AppBox.app/Contents/MacOS/AppBox ipa=$IPA_FILE email='user@example.com'
```

**Comment by satheeshpayoda** [comment]
Thanks for your answer. 
I tested its working fine now with latest version. JFYI, First i tested with old version. It hangs at Update dialog even with email= argument. i hope you have fixed this on latest version. So on next release , it will not hangs at Update dialog.

My Humble Request: 
You should allow us to upload IPA alone to DropBox without any email notification. ("email=")
Because you are using your own SMTP to send mails when upload completed. So you can see the mails with link to app from your side. Some people don't want their app to be public until it become stable or app might be only for internal use etc...

Thanks.

**Comment by vineetchoudhary** [comment]
That's not completely true. AppBox use mailgun to send mail and mailgun doesn't provide any way to see body content of an email. 

Also, mailgun only retains 3-day mail logs in which I can only check mail subject, recipient and delivery status.

**Comment by vineetchoudhary** [comment]
Also, I'll make `email` argument optional in next release. 🤘🏻🤘🏻

**Comment by satheeshpayoda** [comment]
Thanks. Hope next release will be released ASAP. ;)

**Comment by vineetchoudhary** [comment]
Yes. Hopefully this weekend.

**Comment by vineetchoudhary** [comment]
Released in [2.8.2](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.8.2).

**Comment by satheeshpayoda** [comment]
Thanks for the new release. Tested and its working fine.

**Comment by anhhtbk** [comment]
Can I use keep_same_link=true? I try but it is not working.
