### ISSUE TITLE
Installation without UDID

### ISSUE THREAD

**Issue by Furkapone** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#172]
First of all, thank you for AppBox, but I have problem to install my app. I press to "install" but it doesn't install. My profile expiration is in 12.04.2020. I think my UDID is not in the profile or something like that. I want to send my game to everyone how can I do it? A method or option in AppBox could be very nice!

**Comment by vineetchoudhary** [comment]
There is only one way. You've to enroll in [Apple Enterprise Program](https://developer.apple.com/programs/enterprise/) and then generate enterprise build instead of ad-hoc. 

This feature only available in enterprise account.

**Comment by Furkapone** [comment]
Thank you very much. I have already a developer account but I don't want to distribute my app in AppStore. Anyway thank you!:)

**Comment by vineetchoudhary** [comment]
If you don't want to distribute via AppStore then Apple Enterprise Program is good for you to reach a large number of users.
