### ISSUE TITLE
How can i login my apple connect account with Apple's TWO-FACTOR AUTHENTICATION

### ISSUE THREAD

**Issue by Peter-Huang0623** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#173]
I want upload my app to apple connect and it requires me to login my apple account. When i click login, it returns me an error code 409. i did receive an AUTHENTICATION code from apple, but nowhere to input. How can i solve this?

**Comment by vineetchoudhary** [comment]
Hi, you need to generate app specific password. You can read more about the same [here](https://support.apple.com/en-in/HT204397).

**Comment by Peter-Huang0623** [comment]
> Hi, you need to generate app specific password. You can read more about the same [here](https://support.apple.com/en-in/HT204397). Let me know if you face any other issue.

i've generated an app specific password, but it tells me ‘Invalid username and password combination’ every time i click login. i wear to gold i've entered my apple connect account correctly.

**Comment by vineetchoudhary** [comment]
Hi, I forget to tell you. There is a button ***Use without Login*** please use that after that click ***Continue without Login*** in next pop-up. That will save you password in your system keychain and will use when you'll try to upload an app to AppStore Connect / Testflight.

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no further response. Please reach out if you have or find the answers we need so that we can investigate further.
