### ISSUE TITLE
The OTA installation cannot finish

### ISSUE THREAD

**Issue by wilwillyy** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#175]
hello, can you help me.
i try to install application with ota link, but the OTA installation cannot finish.
how to fix this?
[image](https://scontent-sin2-1.xx.fbcdn.net/v/t1.0-9/69257531_10214059043541293_8807201117600481280_n.jpg?_nc_cat=108&_nc_oc=AQkyV4LOtPbPC_DTnj2lCG-QN3Zg2GcfG_m4xm-Tg8Bp6GQ-zbQjukFVbSL-hwQyejA&_nc_ht=scontent-sin2-1.xx&oh=f378bad0bb159c2e3495788f484ef533&oe=5E0B1088)

**Comment by vineetchoudhary** [comment]
Hi, There might be many reasons for this issue. Can you share your app link? If you want to keep link private between us you can also share via email vineetchoudhary[at]live.in.

Also, If you don't want to share the link let me know the following info - 
- AppSize 
- Country (In which you are trying to install)
- Your network conditions (like speed, wifi / mobile data etc)

**Comment by wilwillyy** [comment]
Hi, thx for reply. 
Please check your email :)

**Comment by schreiby** [comment]
> hello, can you help me.
> i try to install application with ota link, but the OTA installation cannot finish.
> how to fix this?

I also had this issue. I uploaded my signed AppStore build and the app would not complete the installation on my device. Am I supposed to use a debug build? 
Also, if yes, does that limit my app installation to only the users on my provisioning profile?
Thank you.

**Comment by vineetchoudhary** [comment]
Hi @schreiby, you can't install AppStore signed build via OTA. Your build must be signed either via development, ad-hoc or enterprise provisioning profile.

**Comment by schreiby** [comment]
Thank you for clarifying. I guess number of devices that I can install on are then dependent on the type of provisioning file I have.

**Comment by vineetchoudhary** [comment]
Yes. If you want to install on any iOS device then you should go for the enterprise provisioning profile. But this will require an [enterprise account](https://developer.apple.com/programs/enterprise/).

**Comment by schreiby** [comment]
Thank you, @vineetchoudhary.

**Comment by vineetchoudhary** [comment]
Hi @wilwillyy, I'm still trying to find the issue you are facing but still no success. Currently, as per my thinking, this is a signing related issue. Can I know how you are generating this IPA file? 

![IMG_1812](https://user-images.githubusercontent.com/8479436/64550061-b095df80-d34f-11e9-8946-fc19e60eba77.PNG)

**Comment by wilwillyy** [comment]
Hi, my problem is enterprise account. Case close :)
I'm generating ipa file to my phone and i rebuild to ipa with ext3nder.
