### ISSUE TITLE
AppBox - Error "crc check failed for file"

### ISSUE THREAD

**Issue by Anvi48** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#189]
Hello!

First of all thank you for your work.
I use your app about 2 years. Every thing was perfect except today.

I resign my projects with new certificate and try to upload it to Dropdox by using AppBox.
And one project can't be uploaded because of this error.
AppBox - Error "crc check failed for file"
I press "OK", application write "Extracting files" and thats all.

It happens only with one project. Other 2 uploaded perfectly. But they are all the same, just clones of each other with different names.

1. Which AppBox version are you using? 
Version 2.9.0 (1)
2. Which macOS version did you experience the issue on?
    - [ ] macOS 10.15.2
   

![Снимок экрана 2020-01-17 в 14 36 19](https://user-images.githubusercontent.com/46524552/72612671-78765d00-393e-11ea-8030-3ba888e21c8f.png)
![Снимок экрана 2020-01-17 в 15 21 45](https://user-images.githubusercontent.com/46524552/72612672-790ef380-393e-11ea-9686-a7b15b5ed446.png)

## AppBox Logs
DropBox Used Space : 4MB
DropBox Available Space : 10624MB
Extracting Files...
ALERT -
Title - AppBox - Error Message - crc check failed for file

Thank You :)

**Comment by vineetchoudhary** [comment]
Hi,

AppBox uses [ZipArchive](https://github.com/ZipArchive/ZipArchive) 3rd party to extract information from the IPA file. Looks like this is the issue which you are facing - https://github.com/ZipArchive/ZipArchive/issues/359

Can you provide me that IPA so I can test? You can also email me on vineetchoudhary[at]live.in

**Comment by Anvi48** [comment]
Hi.
The problem was solved by reinstalling the app.

**Comment by vikas-chandra-mnnit** [comment]
After upgrading the macOS to Catalina I have started facing this issue. I am using AppBox version Version 2.9.1 (1).

**Comment by hiren-torinit** [comment]
I am facing the same issue too even with latest appbox release

**Comment by wammy67** [comment]
same here

**Comment by hafizshoaibawan** [comment]
> Try restarting your local machine.

It worked for me.

**Comment by fcrmlk** [comment]
how to get rid of this Bus my last build was uploading an hour ago and now its not uploading
