### ISSUE TITLE
Universal app with deployment target iOS 11.0 is not installing on iOS 13.3 mobile phones. It's downloading from appbox using safari. When click on it not responding.

### ISSUE THREAD

**Issue by viswanath3344** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#190]

**Comment by ecufre** [comment]
I'm having the same issue on some devices.
Iphone 6s - Software version: 13.3.1
Iphone 7 - Software version: 13.5.1

It's downloading from appbox using safari, but It's not installing on the phone.
![WhatsApp Image 2020-06-17 at 14 00 59](https://user-images.githubusercontent.com/41978806/84927973-07310680-b0a4-11ea-8f9a-4853f105cd58.jpeg)

then if I press the icon the following pop up appears
![WhatsApp Image 2020-06-17 at 14 02 51](https://user-images.githubusercontent.com/41978806/84928119-465f5780-b0a4-11ea-9ecf-9ef8e1b23dfc.jpeg)

macOs version: 10.15.4
AppBox version: 2.9.0

This problem only happens on some phones. In most cases the app was downloaded and installed correctly.

**Comment by vineetchoudhary** [comment]
Hi @ecufre,

Please make sure you've added your device UDID (in which installation is falling) on your Apple Developer Account. Also please check this issue for more details - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/112

I hope this will help you. Also, please let me know if you've any other questions regarding this.

**Comment by ecufre** [comment]
I added the device UDID as you indicated and uploaded a new version.
But when I check the build in the dashboard I find that I have the same amount of devices that I had before
<img width="643" alt="Captura de Pantalla 2020-06-18 a la(s) 12 30 20" src="https://user-images.githubusercontent.com/41978806/85041445-52105400-b160-11ea-8be0-33c2d3f4b827.png">

Does it take time for the AppBox to register the added devices or do i have to download the apple certificates again?

**Comment by vineetchoudhary** [comment]
Hi,

For that, you've to click on the "Show in Finder" button (as you can see in the screenshot of your comment) and delete the existing provisioning from your system. After that download the updated provisioning profile with newly added devices. Then simple open that provisioning profile in your system to install that. This way we'll be 100% sure we are using latest provisioning profile.

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no further response from the author. If the above solution doesn't work, please reach out so that we can investigate further. 

Thank you 😊
