### ISSUE TITLE
Unable to install Expo iOS app

### ISSUE THREAD

**Issue by oebilgen** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#192]
Steps:

1. Build an Expo iOS app https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40base64ai/base64ai-c950c1d3-6919-4da7-b484-fdfcbd75abd5-archive.ipa
2. Use AppBox to distribute
3. Download the app to iPhone (latest iOS)

Actual:
* The app downloads but does not launch with "Unable to download" error message
* The icon is blank

![IMG_8672](https://user-images.githubusercontent.com/1641185/77683403-b612ea00-6f6e-11ea-8d16-4f14839ba152.PNG)

**Comment by vineetchoudhary** [comment]
Hi @oebilgen,

I checked your IPA file and find that your app is signed with an AppStore distribution provisioning profile. So, that why you are not able to install it. With AppBox, you can only install an app signed with development, ad-hoc and In-house (Enterprise) provisioning profile.

Thanks,
