### ISSUE TITLE
How to reset Dashboard

### ISSUE THREAD

**Issue by gb160** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#198]
Hi, im trying to reset the dashboard, and start again from scratch.

Any advice on how to do this?

Ive deleted the app and all supporting files, deleted everything from my dropbox, but when I reinstall appbox the same builds are still there.

Cheers

**Comment by vineetchoudhary** [comment]
Hi,

This folder `~/Library/Containers/com.developerinsider.AppBox` contains all files that AppBox store locally in your system. Deleting this folder reset AppBox Dashboard and other AppBox things to the default state. 
<img width="882" alt="Screenshot 2020-07-10 at 2 44 41 PM" src="https://user-images.githubusercontent.com/8479436/87138395-fac35680-c2bb-11ea-97d3-9d53913fb22b.png">


Also, you can find Dropbox auth token in your keychain. Just search AppBox in keychain in All Items category and delete following entry `com.developerinsider.AppBox.dropbox.authv2` -
<img width="1280" alt="Screenshot 2020-07-10 at 2 41 47 PM" src="https://user-images.githubusercontent.com/8479436/87138252-c8195e00-c2bb-11ea-8c52-d6abf8f6982e.png">

**Comment by gb160** [comment]
Many thanks buddy, Ill try that now.

**Comment by gb160** [comment]
Hmmmn, that folder doesn't exist on my system:

<img width="1391" alt="Screenshot 2020-07-10 at 10 33 58" src="https://user-images.githubusercontent.com/2493592/87140151-f0439580-c298-11ea-8dd4-8c7c2aaad221.png">

**Comment by gb160** [comment]
Edit: However I've deleted `com.developerinsider.AppBox` from the `~/Library/Application Support` directory and that has indeed reset the dashboard.

Thanks for your assistance.

**Comment by vineetchoudhary** [comment]
**Great 👍**

but this is weird. In my system `~/Library/Application Support/com.developerinsider.AppBox` only contains crashes data. 🤷‍♂️

**Comment by gb160** [comment]
Not sure buddy, I'm running macOS 10.15.5, and installed with `curl -s https://getappbox.com/install.sh | bash`
