### ISSUE TITLE
unable to download app

### ISSUE THREAD

**Issue by dkliman** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#21]
I was able to get my app onto several devices, but on one iPad, I got this error message. Will it only work on provisioned devices in my dev account? I'm not sure what to do to fix this problem.

![unable-to-download](https://cloud.githubusercontent.com/assets/672232/21465061/03f154c6-c9c5-11e6-9ab5-5236b9d37b67.PNG)

**Comment by dkliman** [comment]
sorry, but I've figured this one out, and it's sad, lol... so only devices that i've previously added as beta devices can receive an app? unless I get an enterprise developer account? sigh.

**Comment by vineetchoudhary** [comment]
Yes, you're right. You need to add your device UDID in ad-hoc provesioning-profile and then again need to download & install that provesioning-profile. Or you can use enterprises account. Here the complete guide https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingProfiles/MaintainingProfiles.html
