### ISSUE TITLE
Access Blocked!

### ISSUE THREAD

**Issue by tiendaik** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#210]
I'm using Appbox to upload ipa file for my testing team. It's working fine then suddenly today I can't access appbox web after click install link. It's show me like below:

Access Blocked!

Sorry!

Your access to this website has been blocked due to invalid activities from your device or IP address. Please try again with some different device or networks. If you think this is mistaken then please open an issue here

![image](https://user-images.githubusercontent.com/18645916/109609525-05d63a00-7b5e-11eb-9db8-5eb6323534f4.png)

Please help!

**Comment by vineetchoudhary** [comment]
Hi, There was a payment issue with firebase which is resolved now please try again. If you are still facing the same issue please let me know here in this issue - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/209
