### ISSUE TITLE
Access Blocked

### ISSUE THREAD

**Issue by ashish7-iOS** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#212]
Steps performed
- ipa link is created from app-box
- When opening the link , it shows following error
[
<img width="966" alt="Screen Shot 2021-03-02 at 12 34 09 PM" src="https://user-images.githubusercontent.com/44750155/109609567-9ce9c480-7b53-11eb-8780-7b288368bdd3.png">
](url)

- I did checked on dropbox folder, the ipa link is not created there as well

**Comment by ashish7-iOS** [comment]
Access Blocked issue is resolved, but there is an installation issue.
- When tapped on install an application, it doesn't popup installation dialog.
![IMG_A2097354B32E-1](https://user-images.githubusercontent.com/44750155/109611737-cbb56a00-7b56-11eb-8972-04cd2909b470.jpeg)

**Comment by vineetchoudhary** [comment]
Hi, There was a payment issue with firebase which is resolved now please try again. If you are still facing the same issue please let me know here in this issue - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/209

For installation issues, please check your provisioning profile and open another issue if the provisioning profile is correct.
