### ISSUE TITLE
Sorry!  Your access to this website has been blocked due to invalid activities from your device or IP address. Please try again with some different device or networks. If you think this is mistaken then please open an issue here

### ISSUE THREAD

**Issue by ShardaPrasad** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#213]
Sorry!  Your access to this website has been blocked due to invalid activities from your device or IP address. Please try again with some different device or networks. If you think this is mistaken then please open an issue here

**Comment by vineetchoudhary** [comment]
Hi, There was a payment issue with firebase which is resolved now please try again. If you are still facing the same issue please let me know here in this issue - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/209
