### ISSUE TITLE
Access Blocked

### ISSUE THREAD

**Issue by MahhmoudFekrySure** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#214]
## Description
Access Blocked 
## Steps to Reproduce
when open link it get
<img width="966" alt="109609567-9ce9c480-7b53-11eb-8780-7b288368bdd3" src="https://user-images.githubusercontent.com/65539032/109610452-7583ff00-7b35-11eb-8cd3-7f89ef6ed892.png">

**Comment by vineetchoudhary** [comment]
Hi, There was a payment issue with firebase which is resolved now please try again. If you are still facing the same issue please let me know here in this issue - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/209
