### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by youthman1987** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#216]
Hi!

i got a Problem with Appbox.
i got this message:
Sorry!

Your access to this website has been blocked due to invalid activities from your device or IP address. Please try again with some different device or networks. If you think this is mistaken then please open an issue here

whats happening?

thanks
Patrick

**Comment by vineetchoudhary** [comment]
Hi, There was a payment issue with firebase which is resolved now please try again. If you are still facing the same issue please let me know here in this issue - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/209
