### ISSUE TITLE
iOS install popup did not appear

### ISSUE THREAD

**Issue by RedWizard89** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#217]
Form yesterday, when I try to use my link from AppBox for direct download, the page don't show the iOS popup proposing to install "xxxapp".

I don't have the same app installed on device from AppStore or other method.

**Comment by gb160** [comment]
Yes I've noticed this issue this morning also.

**Comment by ashish7-iOS** [comment]
I am facing the same issue since morning.

**Comment by vineetchoudhary** [comment]
Hi All,

A fix has been deployed for this issue on the [AppBox Installation Web App](https://github.com/getappbox/WebApp). This was happening due to a Dropbox direct download (dl.dropbox.com) domain redirection change. Previously dl.dropbox.com get redirected to the dl.dropboxusercontent.com automatically but now we've to make a direct request to dl.dropboxusercontent.com.

<img width="1721" alt="Screenshot 2021-03-02 at 3 18 33 PM" src="https://user-images.githubusercontent.com/8479436/109630998-8ea7a280-7b6b-11eb-8e39-f77567b11a15.png">

**Comment by longleeproduction** [comment]
Install successful
Thank you! @vineetchoudhary

**Comment by ashish7-iOS** [comment]
Hello @vineetchoudhary ,

- Install pop-up issue resolved but unable to install the application.

- Error dialog: "**Unable to Install**" appears. 

p.s: I don't have the same app installed on device from AppStore or other method.

**Comment by RedWizard89** [comment]
Same problem, popup is ok but the app show a blank icon and don't install

**Comment by RedWizard89** [comment]
> Hi All,
> 
> A fix has been deployed for this issue on the [AppBox Installation Web App](https://github.com/getappbox/WebApp). This was happening due to a Dropbox direct download (dl.dropbox.com) domain redirection change. Previously dl.dropbox.com get redirected to the dl.dropboxusercontent.com automatically but now we've to make a direct request to dl.dropboxusercontent.com.
> 
> <img alt="Screenshot 2021-03-02 at 3 18 33 PM" width="1721" src="https://user-images.githubusercontent.com/8479436/109630998-8ea7a280-7b6b-11eb-8e39-f77567b11a15.png">

Thank you, now work but app show a blank icon and don't install

**Comment by gb160** [comment]
Yes same issue here, popup appears, but then just a dark icon with 'unable to install'

**Comment by trungnguyen1791** [comment]
It works with iOS 13.2, but the other one with iOS 14.3 get dark gray icon and Unable to install

**Comment by trungnguyen1791** [comment]
@vineetchoudhary I think you should replace dropbox link in manifest file to "https://dl.dropboxusercontent.com" too.

**Comment by vineetchoudhary** [comment]
@trungnguyen1791  yes. But this one, I've to replace inside the main AppBox app. I'll upload a new version of AppBox with this fix.

**Comment by trungnguyen1791** [comment]
@vineetchoudhary ya I see. I've tried to replace the dropbox url in manifest manually as a hot fix :D

**Comment by gb160** [comment]
> @trungnguyen1791 yes. But this one, I've to replace inside the main AppBox app. I'll upload a new version of AppBox with this fix.

Sorry if I come across as impatient but is the updated AppBox app available yet?

Just to be clear I really appreciate this project and the work you do on it...its excellent.

**Comment by vineetchoudhary** [comment]
Hi @gb160, I'm doing some final testing around this fix. It will be available soon.

**Comment by gb160** [comment]
> Hi @gb160, I'm doing some final testing around this fix. It will be available soon.

No problem buddy I appreciate the feedback.

**Comment by vineetchoudhary** [comment]
Hi All, a new version of AppBox (2.9.5) is available to download - 
https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.9.5

Please let me know if you face any issues.

**Comment by gb160** [comment]
> Hi All, a new version of AppBox (2.9.5) is available to download -
> https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.9.5
> 
> Please let me know if you face any issues.

Excellent.

Ive only tested with one app but it worked perfectly.

Thanks again!

**Comment by RedWizard89** [comment]
> Hi All, a new version of AppBox (2.9.5) is available to download -
> https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.9.5
> 
> Please let me know if you face any issues.

Thank you so much, all my links work perfectly

**Comment by longleeproduction** [comment]
Hi @vineetchoudhary 
I want to manual edit manifest.plist ipa link. But not install app.
Is there any solution so I can fix it manually?
Thank you!
