### ISSUE TITLE
Access blocked

### ISSUE THREAD

**Issue by stavila** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#224]
Hi,
All my appbox links (hosted in dropbox) are now saying access blocked. This happens from any device, any IP. What causes this?

thank you. 

“Sorry!

Your access to this website has been blocked due to invalid activities from your device or IP address. Please try again with some different device or networks. If you think this is mistaken then please open an issue here”

**Comment by vineetchoudhary** [comment]
Hi,

Sorry for the inconvenience. This issue has been fixed please check again.
