### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by RadheshyamStws** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#228]
Appbox build uoploaded not working
![Screenshot 2021-04-16 at 6 39 42 PM](https://user-images.githubusercontent.com/78482383/115029013-288c9a00-9ee3-11eb-9aab-ca83b8088560.png)

**Comment by vineetchoudhary** [comment]
Hi,

Sorry for the inconvenience. This issue has been fixed please check again.
