### ISSUE TITLE
Access Blocked for Users

### ISSUE THREAD

**Issue by smartservProduct01** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#229]
![Screen Shot 2021-04-16 at 7 43 10 PM](https://user-images.githubusercontent.com/82663299/115037331-fb90b500-9eeb-11eb-8c71-bfe996b74617.png)

**Comment by smartservProduct01** [comment]
Not Working

**Comment by vineetchoudhary** [comment]
Hi,

Sorry for the inconvenience. This issue has been fixed please check again.
