### ISSUE TITLE
Dropbox issues 

### ISSUE THREAD

**Issue by ctrlcmdshft** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#240]
Dropbox won't stay logged into appbox every time I open appbox I need to re connect dropbox

**Comment by vineetchoudhary** [comment]
Hi @ctrlcmdshft 

Please make sure you have provided keychain access to the AppBox. AppBox stores Dropbox authentication token in Keychain. So, try to reinstall the AppBox and provide keychain access to Appbox stored information.

**Comment by evlsmurf** [comment]
Ok I will give that a try later.

**Comment by ctrlcmdshft** [comment]
I'll give that a try later thanks!
