### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by vineetchoudhary** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#37]
- Create CoreData Model for complete project data and dropbox links
- Save Metadata for uploaded file on Dropbox for managing (Delete) that in feature
- Create Dashboard UI
- Update `AppInfo.json` based on user action in dashboard
- Keep uploaded app details and CI integrated project details in different section

**Comment by Sam-Ryan** [comment]
Nice features! ✌🏽️

**Comment by vineetchoudhary** [comment]
**Released in Version 2.0.1** - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.0.1
