### ISSUE TITLE
Attention!

### ISSUE THREAD

**Issue by hemangshah** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#63]
I hope you're aware of this.

https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/

**Comment by vineetchoudhary** [comment]
Yes, I know this. But I'm using a separate download [URL](http://www.tryappbox.com/download). So, I just need to change download URL at only one place. I'll change this before 15Aug.

[AppBox Download Page](https://github.com/tryappbox/tryappbox.github.io/blob/master/download.md)

Thanks for bringing my attention to this.
