### ISSUE TITLE
Deleted builds are accesible

### ISSUE THREAD

**Issue by pallaviMN** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#65]
Hi,
i made "Keep Same Link" while uploading ipa to Appbox for 3 different version. Tried to access that link in safari. I was able to see 3 old version. Now i went to dropbox & deleted one of the version. In iPad, again refreshing safari still shows that old link as well to install.

**Comment by pallaviMN** [comment]
Should i edit appinfo.json as well in dropbox inorder for that reflect?

**Comment by vineetchoudhary** [comment]
Yes, you need to edit the appinfo.json.

**Comment by vineetchoudhary** [comment]
I'm planning to add the Dashboard #37 . In which I'll add this functionality, where user will able to delete app directly from AppBox.

**Comment by Sam-Ryan** [comment]
That's Nice man 👍🏽

**Comment by vineetchoudhary** [comment]
Hi,

I've implemented the delete feature. Now you can delete any build right from the Dashboard. Please update to the latest version -
https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.0.1

Thanks,
