### ISSUE TITLE
Custom Description on download Page

### ISSUE THREAD

**Issue by Sam-Ryan** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#67]
Hello Man, im looking for adding A description when people choose to download ipa from AppBox, is it possible to change The default redirection description ? 
Warmly

**Comment by vineetchoudhary** [comment]
Hi, Please check this issue #14

**Comment by Sam-Ryan** [comment]
Nice Thanks. Btw is it possible to add download statistics & analytics?

**Comment by vineetchoudhary** [comment]
Yes. You can use [google analytics](https://analytics.google.com/) for web.

**Comment by vineetchoudhary** [comment]
Also, you can just append the `.info` in Google shortener url, which generated by AppBox.

Like, if you build short url is [https://goo.gl/nN0ds6](https://goo.gl/nN0ds6) then you need to visit [https://goo.gl/nN0ds6.info](https://goo.gl/nN0ds6.info) for statistics.

**Comment by Sam-Ryan** [comment]
That's nice thanks man :)
