### ISSUE TITLE
To check number of users installed

### ISSUE THREAD

**Issue by pallaviMN** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#70]
Hi,

Is there any way to check how many users have installed the app & on which device & its version?

Regards
Pallavi M N

**Comment by vineetchoudhary** [comment]
Hi,

No, currently there is now way to check the number of installation or device etc. But, you can get short url statistics by just appending the .info in Google shortener url, which generated by AppBox.

Like, if your build short url is https://goo.gl/nN0ds6 then you need to visit https://goo.gl/nN0ds6.info for statistics.

**Comment by vineetchoudhary** [comment]
Hi,

I've update the AppBox. Please update to the latest version. New version include Dashboard, AppStore Upload, Preferences for Gmail, Xcode & Slack. Check all the changes here - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.0.1

Thanks,
