### ISSUE TITLE
Fastlane integration

### ISSUE THREAD

**Issue by iamabhiee** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#71]
Hi, This app is very useful, it would be more helpful to automate workflow if its possible to use it with fastlane.

**Comment by vineetchoudhary** [comment]
Hi @iamabhiee , 
I'm working on Jenkins integration. After this, I'll surely add support Fastlane tool in near future.

Integrate AppBox with Jenkins - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/wiki/Setup-Jenkins

**Comment by vineetchoudhary** [comment]
Initial release is here - https://rubygems.org/gems/fastlane-plugin-appbox

**Comment by vineetchoudhary** [comment]
Stable release available here - https://github.com/getappbox/fastlane-plugin-appbox 🥇 💯
