### ISSUE TITLE
Cannot see All Previous Builds in web page

### ISSUE THREAD

**Issue by giabao0212** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#80]
Hi AppBox team,

I have downloaded the latest stable release of AppBox and did upload several builds using it.However, now i cannot see any option to see previous builds when opening the webpage from the downloadable link of .ipa. It appears to be like this:
 
https://imgur.com/a/X7h9U

**Comment by vineetchoudhary** [comment]
Hi,

You need to select "Keep Same Link" option.
<img width="732" alt="screen shot 2017-11-02 at 8 36 32 pm" src="https://user-images.githubusercontent.com/8479436/32333935-1dec8e18-c00f-11e7-9a67-6c5e5e02a425.png">


Read more about this here - http://www.tryappbox.com/features/keepsamelink
