### ISSUE TITLE
more storage options

### ISSUE THREAD

**Issue by Dry05** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#82]
Hi could you include more storage options than dropbox like mega? thanks so much for this tool btw it's great.

**Comment by vineetchoudhary** [comment]
Hi, Mega doesn't have any macOS SDK but I'll try to use their native [C++ sdk](https://github.com/meganz/sdk).

**Comment by Dry05** [comment]
Hi thanks so much! One little question left, I’m trying to upload kodi.ipa but I’m getting ‘can’t be able to find info.plist’ but it’s just in there tried multiple kodi versions. Any ideas? It’s the only app with that problem

**Comment by djankey** [comment]
Google Drive support?

**Comment by ipwnosx** [comment]
Yes I gotta say, great concept but won’t install even presigned apps. However apps install with other services.... so idk..  however an iOS version of this would be coo

**Comment by RemyLivewall** [comment]
Would love to see Google Drive support. We use AppBox primarily for larger apps above 100MB and we use Google Drive more frequently internally.

**Comment by vineetchoudhary** [comment]
**Google Drive** - The main problem with google drive and other storage options they didn't provide a direct download link. In iOS, the app manifest file should be downloaded without any redirection. That's why AppBox only supports Dropbox. I remembered when I started this project I've tried to integrate Google drive but there was no success at that time. I'll look again. Also, if you know some workaround pls let me know.

**Box.com** - I don't have any experience with box.com. So, first, I've to perform some test with Box.com. But as per my first look, they didn't provide 250+ MB upload service for free accounts. On another hand, Dropbox doesn't have such kind of limitation.

**Comment by RemyLivewall** [comment]
> **Google Drive** - The main problem with google drive and other storage options they didn't provide a direct download link. In iOS, the app manifest file should be downloaded without any redirection. That's why AppBox only supports Dropbox. I remembered when I started this project I've tried to integrate Google drive but there was no success at that time. I'll look again. Also, if you know some workaround pls let me know.
> 
> **Box.com** - I don't have any experience with box.com. So, first, I've to perform some test with Box.com. But as per my first look, they didn't provide 250+ MB upload service for free accounts. On another hand, Dropbox doesn't have such kind of limitation.

I'm not sure if this helps at all, but I found this webapps stack answer which might help: https://webapps.stackexchange.com/questions/30654/in-google-drive-how-can-you-link-directly-to-download-a-zip-file-and-not-view
Here is a more detailed article describing some options and with more explaining: https://www.labnol.org/internet/direct-links-for-google-drive/28356/

**Comment by vineetchoudhary** [comment]
@RemyLivewall thanks for the links. But we can't skip google drive virus scan warning if IPA file size is greater than 100MB. As per them 

> Only files smaller than 100 MB can be scanned for viruses. For larger files, a warning is displayed saying that the file can't be scanned.

This weekend, I'll try this manually first. If everything goes well I'll implement in AppBox.

**Comment by vineetchoudhary** [comment]
Today, I ran several manual tests for google drive but no success. I think iOS need a direct manifest.plist file path without any redirection. Also, seems like if URL doesn't contain manifest.plist then iOS will ignore that URL straightforward. 

Here the test URL I've used - 
```
itms-services://?action=download-manifest&url=https://drive.google.com/uc?export=download&id=18HjjyIBJ69eq60Eo5RbERZZulORlgGeX
```

Here the logs from iPhone 7, As you can see there is no request to `google.com` from iOS when I tapped on installation URL - 
![screenshot 15](https://user-images.githubusercontent.com/8479436/47601090-f7edd880-d9e8-11e8-9de3-e6ab8d0eb8d0.png)

Also, here the logs from the same device, As you can see here iOS request manifest file from `dropbox.com` and initiated `NSURLSession` to download IPA file - 

![screenshot 16](https://user-images.githubusercontent.com/8479436/47601085-f1f7f780-d9e8-11e8-94be-807b9bd1af53.png)

So, It seems like google drive is not an option for AppBox.

**Comment by rizwan95** [comment]
What about providing Custom drive support? @vineetchoudhary

**Comment by vineetchoudhary** [comment]
It is a little bit hard to find a good and free 3rd party service to cover our use cases. So, closing this issue. 

In the near future, we are going to support CDN or VPS services like S3, Digitial Ocean Spaces.
