### ISSUE TITLE
Unable to install the app from the url

### ISSUE THREAD

**Issue by techiepop** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#84]
i was trying to install the app from the url  after downloading some part it is displaying that downloading failed. This is happening for UAE region

**Comment by vineetchoudhary** [comment]
Hi, I don't this is a region based issue. Please provide following details, so I can reproduce this issue. 
- Device details (like- iPad/iPhone, iOS version)
- Alert message text or screenshot
- Build type (ad-hoc, development or enterprise )
- For ad-hoc, please make sure device UDID present in provisioning profile
- Build share URL (you can email me at [vineetchoudhary@live.in](mailto:vineetchoudhary@live.in)

**Comment by techiepop** [comment]
- Device details :* Iphone 7,6s,6,Ipad  OS version 11.1.1*
   - Alert message text or screenshot : *Unable to download app, or
   waiting *
   - Build type (ad-hoc, development or enterprise ) : *ad-hoc*
   - For ad-hoc, please make sure device UDID present in provisioning
   profile  : *ALL UDIDS ARE ADDED*
   - Build share url : https://goo.gl/6Cr8RM

**Comment by jryanhaber** [comment]
Hi!  

I am having the same issue.  I created the app in react native via expo xde, tested on my phone,  its working, and then exported to an ipa and uploaded it here.  

Then I downloaded to an iphone 6 plus on the latest ios. 

The first time the upload worked, but does not show up in the dashboard... 

On download to phone I get "this app could not be downloaded at this time" or something close to that. 

On second upload:
![image](https://user-images.githubusercontent.com/167328/33224309-142c4b9c-d11d-11e7-978e-67d1f76225e1.png)

on third upload attempt:
![image](https://user-images.githubusercontent.com/167328/33224334-5289333c-d11d-11e7-940e-0f91f5d4e17e.png)

And then it 'quit unexpectedly' when showing me the link.. 

not sure the build type, how can I check this?

Build share url: https://goo.gl/b9SXPM

**Comment by vineetchoudhary** [comment]
@jryanhaber this issue fixed in latest release. Now, I'm uploading large size IPA file chunk. You can set chunk size from AppBox Preferences (⌘ + ,). The default size is 100MB, means AppBox will upload IPA file with 100MB partitions.

**Comment by ShambhooSevenstar** [comment]
The Application "Appbox "can't be opened
