### ISSUE TITLE
Possible Enhancements

### ISSUE THREAD

**Issue by hemangshah** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#89]
Hi Vineet, as I can read [here](http://www.tryappbox.com/features/faq/CheckDownloadStatisticsAndAnalytics.html), you can add a new option like "See Statistics" and when user select it, you can redirect him to the goo.gl URL by adding ".info". This will actually give them access to see the statistics of their app and you don't need to worry about the stats of a URL.

Please share your feedback.

**Comment by vineetchoudhary** [comment]
AppBox dashboard already have this. Please download the latest version.

![screen shot 1](https://user-images.githubusercontent.com/8479436/34373031-bf84f2e6-eafe-11e7-97fa-905cfa835793.png)

**Comment by vineetchoudhary** [comment]
AppBox Dashboard already have this. You can open dashboard using from `File>Dashboard` or `⌘ + D`. Please download latest version.
![screen shot 1](https://user-images.githubusercontent.com/8479436/34373110-2218ff24-eaff-11e7-915f-a6877cdcb90d.png)
